# Generated by Django 4.2.7 on 2026-05-11 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=100, verbose_name='Nom de la filière')),
                ('code_filiere', models.CharField(max_length=10, verbose_name='Code de la filière')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom_filiere'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code_matiere', models.CharField(max_length=10, verbose_name='Code de la matière')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('volume_horaire', models.PositiveIntegerField(verbose_name='Volume horaire')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom_matiere'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du niveau')),
                ('code_niveau', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code du niveau')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['nom_niveau'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_province', models.CharField(max_length=100, verbose_name='Nom de la province')),
                ('code_province', models.CharField(max_length=10, verbose_name='Code de la province')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['nom_province'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ville', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='core.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom_ville'],
            },
        ),
        migrations.CreateModel(
            name='SupportCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fichier_support', models.FileField(upload_to='supports/', verbose_name='Fichier de support')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='core.enseignant', verbose_name='Enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='core.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Support de cours',
                'verbose_name_plural': 'Supports de cours',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='core.niveau', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(max_length=50, verbose_name='Nationalité')),
                ('niveau_etude', models.CharField(max_length=100, verbose_name="Niveau d'étude actuel")),
                ('etablissement_origine', models.CharField(max_length=200, verbose_name="Établissement d'origine")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etab', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('type_etab', models.CharField(choices=[('universite', 'Université'), ('ecole_sup', 'École Supérieure'), ('institut', 'Institut'), ('centre', 'Centre de Recherche')], max_length=20, verbose_name="Type d'établissement")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='core.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom_etab'],
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='core.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='core.matiere', verbose_name='Matières'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
